import { Router, Request, Response } from 'express';
import { ObjectId } from 'mongodb';
import { getDatabase } from '../db/client.js';

interface StatusResponsibleDoc {
  _id?: ObjectId;
  name: string;
  department: string;
  username?: string;
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
}

interface StatusResponsibleDto {
  id: string;
  name: string;
  department: string;
  username?: string;
}

const RAW_RESPONSIBLES: [string, string, string?][] = [
  ['AILTON LIMA SANTOS OLIVEIRA', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['ALINE ROQUE MAGALHAES', 'DIRETORIA DE DIFUSAO CIENTIFICA E CIDADES INTELIGENTES'],
  ['ANA CAROLINA GONCALVES DA SILVA NUNES', 'SUBSECRETARIA DE FOMENTO A INOVACAO'],
  ['ANA CLARA TAVARES DA SILVA', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['ANDRE FONTENELE FIGUEIREDO', 'ASSESSORIA DE FISCALIZACAO E MONITORAMENTO DE PARCERIAS'],
  ['ANDRESSA JUCA NORONHA', 'GERENCIA DE MATERIAIS'],
  ['ANNY MICHELLY COSTA SANTOS', 'ASSESSORIA DE RELACOES INSTITUCIONAIS E ATEND. A COMUNIDADE'],
  ['ANTONIO ARNALDO DE QUEIROZ CAMPOS', 'GERENCIA DE PATRIMONIO'],
  ['BRUNA PETRONYLLA GOMES DE SOUSA', 'GERENCIA DE RECEBIMENTO E BAIXA'],
  ['BRUNO LIMEIRA TEIXEIRA PINHEIRO', 'DIRETORIA DE JOGOS ELETRONICOS'],
  ['BRUNO MARIANO SOUZA LOPES FROTA', 'DIRETORIA DE LICITACOES'],
  ['CAMILA CASSALTO SOARES ISAAC', 'GABINETE'],
  ['CATARINE MARIA DE SOUSA PINTO MARCAL', 'SECRETARIA EXECUTIVA'],
  ['CLAUDIA SOARES LOPES', 'SUBSECRETARIA DE ADMINISTRACAO GERAL'],
  ['COSME SERGIO ALVES LIMA', 'ASSESSORIA DE GESTAO ESTRATEGICA DE PROJETOS'],
  ['DAYANE FERNANDES VIEIRA', 'ASSESSORIA DE COMUNICACAO'],
  ['DAYANE TAVARES DA SILVA VERAS', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['EDIMILSON ARRUDA DA SILVA', 'GERENCIA DE PESQUISA E RETORNO SOCIAL'],
  ['EDUARDO ALMEIDA CASTRO', 'GERENCIA DE GESTAO DE PESSOAS'],
  ['EMANUELE MARQUES BATISTA', 'ASSESSORIA DE COMUNICACAO'],
  ['FILIPE CAMPOS MENDES', 'SUBSECRETARIA DE ADMINISTRACAO GERAL'],
  ['FILIPE CARVALHO LOPES', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['FRANCIELLY FIGUEIREDO OSORIO', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['GABRIEL GADELHA MARQUES', 'DIRETORIA DE ORCAMENTO E FINANCAS'],
  ['GABRIEL NUNES PAVANELI', 'GABINETE'],
  ['GABRIELLA OLIVEIRA TAVARES', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['GERSON BERBET JUNIOR', 'DIRETORIA DE DIFUSAO CIENTIFICA E CIDADES INTELIGENTES'],
  ['GILBERTO KEIJI HARAGUCHI', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['GILMA XIMENES FEITOZA', 'DIRETORIA ADMINISTRATIVA'],
  ['GIOVANNA DE ARAUJO DOURADO', 'DIRETORIA DE DIFUSAO CIENTIFICA E CIDADES INTELIGENTES'],
  ['GREICIELEN OLIVEIRA PORTUGUEZ', 'DIRETORIA DE CAPACITACAO E INCLUSAO DIGITAL'],
  ['GUILHERME GOMES DO PRADO', 'SECRETARIA EXECUTIVA'],
  ['GUSTAVO ALVES GOMES', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['GUSTAVO GERALDO PEREIRA MACHADO', 'ASSESSORIA JURIDICA-LEGISLATIVA'],
  ['GUSTAVO MELO WERNIK', 'GERENCIA DE PESQUISA E RETORNO SOCIAL'],
  ['HEBER AMERICO MACEDO', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['HENNY KAMILLA RAMOS DE LIMA', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['HENRIQUE DO VALE ROCHA FILHO', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['IDOMAR CUSTODIO DA SILVA JUNIOR', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['IGOR ALBUQUERQUE DE BRITO', 'GABINETE'],
  ['IONIO RODRIGUES SERRALHA NETO', 'DIRETORIA ADMINISTRATIVA'],
  ['JANAINA GOMES DA SILVA', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['JECIANE SEREJO BERNARDINO', 'GERENCIA DE FROTA'],
  ['JOAO VITOR NASCIMENTO DOS REIS CARDOSO', 'GERENCIA DE GESTAO DE PESSOAS'],
  ['JOSE PEREIRA DA SILVA', 'GERENCIA DE DOCUMENTOS'],
  ['KAMILA NASCIMENTO RANGEL', 'OUVIDORIA'],
  ['KAMILLA RIBEIRO DE ASEVEDO', 'ASSESSORIA JURIDICA-LEGISLATIVA'],
  ['LARISSA LAINE HIPOLITO ALVES', 'ASSESSORIA DE CAPTACAO DE RECURSOS', 'larissa.hipolito'],
  ['LAURA FERNANDES FERREIRA', 'DIRETORIA DE CAPACITACAO E INCLUSAO DIGITAL'],
  ['LEANDRO BATISTA REIS', 'GABINETE'],
  ['LUCAS CANDEIRA ALBUQUERQUE TEOTONIO', 'DIRETORIA DE ECONOMIA CIRCULAR'],
  ['LUCILIA HELENA PINTO GUNEY', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['LUIS EDVAR CAVALCANTE FILHO', 'GERENCIA DE PESQUISA, DESENVOLVIMENTO E DIFUSAO CIENTIFICA'],
  ['LUIZA MUNIZ PINHEIRO', 'ASSESSORIA DE COMUNICACAO'],
  ['MARCELA TORRES DE AVELLAR', 'ASSESSORIA DE COMUNICACAO'],
  ['MARCELO FALCOMER PONTES FILHO', 'GABINETE'],
  ['MARIA CRISTINA MONTEIRO DE OLIVEIRA', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['MARIANA MOREIRA DO CARMO', 'GABINETE'],
  ['MICHELLE CAMPOS DOS SANTOS', 'ASSESSORIA DE GESTAO ESTRATEGICA DE PROJETOS'],
  ['MILTON MENDES FERNANDES JUNIOR', 'GABINETE'],
  ['MIRELLA CAMELO VIEIRA', 'DIRETORIA DE CAPACITACAO E INCLUSAO DIGITAL'],
  ['MIRON JOSE DE ARAUJO JUNIOR', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['NAYARA HANNA SANTIAGO COSTA', 'GABINETE'],
  ['ODIRLEY DE JESUZ SANTIAGO', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['PATRICIA DE ARAGAO CARVALHO', 'DIRETORIA ADMINISTRATIVA'],
  ['PATRICIA MOUTINHO CORREIA', 'DIRETORIA DE CAPACITACAO E INCLUSAO DIGITAL'],
  ['PATRICIA RAQUEL NUNES SILVA', 'SUBSECRETARIA DE ADMINISTRACAO GERAL'],
  ['PATRICK SQUIPANO MORONARI', 'GABINETE'],
  ['PRISCILA ALVES BARBOSA FERREIRA', 'ASSESSORIA DE RELACOES INSTITUCIONAIS E ATEND. A COMUNIDADE'],
  ['RAFAEL DA SILVA RIBEIRO', 'GERENCIA DE TECNOLOGIA DA INFORMACAO'],
  ['RAFAEL MOREIRA VITORINO', 'SECRETARIA DE ESTADO DE CIENCIA TECNOLOGIA E INOVACAO'],
  ['RAYANA REZENDE LIMA CASQUEIRO', 'ASSESSORIA JURIDICA-LEGISLATIVA'],
  ['RENARA FONSECA CASTRO', 'ASSESSORIA DE CAPTACAO DE RECURSOS'],
  ['RENATA MAYLLA ARAUJO SILVA', 'DIRETORIA DE ORCAMENTO E FINANCAS'],
  ['RENATO ROCHA CARDOSO DA SILVA', 'ASSESSORIA DE FISCALIZACAO E MONITORAMENTO DE PARCERIAS'],
  ['ROBERTO BARROS', 'GERENCIA DE CURADORIA CIENTIFICA DO PLANETARIO DE BRASILIA'],
  ['SAMARA GOMES DE ARAUJO', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['SAMUEL CAMPOS DOS SANTOS ROSA TELES', 'DIRETORIA DE DIFUSAO CIENTIFICA E CIDADES INTELIGENTES'],
  ['THAYNA VALENCA COSTA', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['UILTON JUNIO MAGALHAES SALAO', 'SUBSECRETARIA DE ADMINISTRACAO GERAL'],
  ['VINICIUS DE SANTANA CORREA', 'SUBSECRETARIA DE ADMINISTRACAO GERAL'],
  ['WALESKA BONDADE LIMA', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL'],
  ['WALLACE EUGENIO AMARAL SILVA MOREIRA', 'SUBSECRETARIA DE PROMOCAO A CIENCIA E DESENV. TECNOLOGICO'],
  ['WENDELL LOURENCO MENDES SALES', 'GERENCIA DE CONTRATOS'],
  ['WILLER CANTALLOPS FERREIRA', 'SUBSECRETARIA DE INOVACAO, CAPACITACAO E INCLUSAO DIGITAL']
];

// Exportar para uso em outros módulos (ex: scripts de criação de usuários)
export { RAW_RESPONSIBLES };

let seedPromise: Promise<void> | null = null;

async function ensureSeeded() {
  if (!seedPromise) {
    seedPromise = (async () => {
      const db = await getDatabase();
      const collection = db.collection<StatusResponsibleDoc>('status_responsibles');
      const now = new Date();

      await Promise.all(
        RAW_RESPONSIBLES.map(([name, department, username]) =>
          collection.updateOne(
            { name },
            {
              $set: {
                name,
                department,
                username: username || undefined,
                active: true,
                updatedAt: now
              },
              $setOnInsert: {
                createdAt: now
              }
            },
            { upsert: true }
          )
        )
      );
    })()
      .catch((error: unknown) => {
        seedPromise = null;
        throw error;
      });
  }

  return seedPromise;
}

function serialize(doc: StatusResponsibleDoc): StatusResponsibleDto {
  return {
    id: doc._id instanceof ObjectId ? doc._id.toHexString() : String(doc._id ?? doc.name),
    name: doc.name,
    department: doc.department,
    username: doc.username
  };
}

export const statusResponsiblesRouter = Router();

statusResponsiblesRouter.get('/', async (_req: Request, res: Response) => {
  try {
    await ensureSeeded();
    const db = await getDatabase();
    const collection = db.collection<StatusResponsibleDoc>('status_responsibles');
    const responsibles = await collection.find({ active: { $ne: false } }).sort({ name: 1 }).toArray();
    res.json(responsibles.map(serialize));
  } catch (error) {
    console.error('Failed to list status responsibles', error);
    res.status(500).json({ error: 'Failed to load responsibles' });
  }
});
